### ISSUE TITLE
与 Touhou Little Maid 一起加载时，进入世界崩溃

### ISSUE THREAD

**Issue by mustardwheat** [HomoMC/Homoium#1]
https://mclo.gs/QT2xF9e
新建世界直接崩溃

环境：
homoium-1.0.7
touhoulittlemaid-1.12.2-1.2.5-release

**Comment by HaHaWTH** [comment]
Confirmed. Try disable the lithiumAiGoal Optimize.

**Comment by HaHaWTH** [comment]
Fixed in 1.0.8
