### ISSUE TITLE
Question about compatibility

### ISSUE THREAD

**Issue by Nekonaro** [HomoMC/Homoium#2]
I would like to know how compatible this mod is with other optimisation mods. 

[performant-1.11](https://legacy.curseforge.com/minecraft/mc-mods/performant/files/3511568) - This mod has FastCollisionAndEntityChecks as well as other changes such as slower SwimmingAI, TemptAI and WanderAI.

[AI Improvements 1.12-0.0.1b3 build 3 for 1.12](https://legacy.curseforge.com/minecraft/mc-mods/ai-improvements/files/all?filter-game-version=2020709689%3A6756) - Replaces the EntityLookHelper

[fermiumasm-5.23](https://legacy.curseforge.com/minecraft/mc-mods/fermiumasm/files/5346789) - Fixes Forge's EntityEntry calling a slow Constructor::newInstance call every time an entity spawns, it is replaced with a fast Function::get generated from LambdaMetafactory#metafactory

It's also interesting what exactly that covers 

    lithiumoptimization {
        # Should we optimize ai goal?
        B:optimizeAiGoal=true

        # Should we optimize math?
        B:optimizeMath=true

in your mod

**Comment by HaHaWTH** [comment]
Technically compatible, this mod didn't touch other mods already modified places:/

Less optimizations but more compatibility
